export interface Regulation {
  id: string;
  title: string;
  titleEn: string;
  category: string;
  categoryEn: string;
  type: "law" | "government-regulation" | "minister-regulation" | "finance-regulation" | "guideline";
  year: number;
  status: "active" | "amended" | "replaced";
  summary: string;
  summaryEn: string;
  keyPoints: string[];
  keyPointsEn: string[];
  source?: string;
}

export const REGULATIONS: Regulation[] = [
  {
    id: "uu-13-2003",
    title: "UU No. 13 Tahun 2003 tentang Ketenagakerjaan",
    titleEn: "Law No. 13/2003 on Manpower",
    category: "Undang-Undang Ketenagakerjaan",
    categoryEn: "Manpower Laws",
    type: "law",
    year: 2003,
    status: "amended",
    summary: "Undang-undang pokok yang mengatur segala aspek ketenagakerjaan di Indonesia, termasuk hubungan kerja, pengupahan, PHK, dan perlindungan pekerja. Sebagian pasal telah diubah oleh UU Cipta Kerja.",
    summaryEn: "The primary law governing all aspects of employment in Indonesia, including employment relations, wages, termination, and worker protection. Partially amended by the Job Creation Law.",
    keyPoints: [
      "Landasan hukum utama ketenagakerjaan Indonesia",
      "Mengatur hubungan kerja, PKWT dan PKWTT",
      "Ketentuan pengupahan, waktu kerja, dan istirahat",
      "Pemutusan hubungan kerja dan pesangon",
      "Pembentukan Lembaga Kerjasama Bipartit",
    ],
    keyPointsEn: [
      "Main legal foundation for Indonesian employment",
      "Regulates employment relations, PKWT and PKWTT",
      "Wage provisions, working hours, and rest periods",
      "Termination of employment and severance",
      "Establishment of Bipartite Cooperation Institutions",
    ],
  },
  {
    id: "uu-6-2023",
    title: "UU No. 6 Tahun 2023 tentang Cipta Kerja (Cluster Ketenagakerjaan)",
    titleEn: "Law No. 6/2023 on Job Creation (Employment Cluster)",
    category: "Undang-Undang Ketenagakerjaan",
    categoryEn: "Manpower Laws",
    type: "law",
    year: 2023,
    status: "active",
    summary: "Omnibus law yang merevisi UU 13/2003. Mengubah ketentuan PKWT (maks 5 tahun), upah minimum, pesangon, alih daya, dan TKA. Berlaku sejak 31 Maret 2023.",
    summaryEn: "Omnibus law amending Law 13/2003. Changes provisions on PKWT (max 5 years), minimum wage, severance, outsourcing, and foreign workers. Effective from March 31, 2023.",
    keyPoints: [
      "PKWT maksimal 5 tahun (termasuk perpanjangan)",
      "Penghapusan upah minimum sektoral",
      "Perubahan rumus pesangon PHK",
      "Relaksasi alih daya (outsourcing)",
      "Kemudahan investasi TKA dengan syarat tertentu",
    ],
    keyPointsEn: [
      "PKWT maximum 5 years (including extensions)",
      "Elimination of sectoral minimum wages",
      "Changes to severance formula",
      "Outsourcing relaxation",
      "Eased foreign worker investment with conditions",
    ],
  },
  {
    id: "pp-35-2021",
    title: "PP No. 35 Tahun 2021 tentang PKWT, Alih Daya, Waktu Kerja, dan PHK",
    titleEn: "Government Regulation No. 35/2021 on PKWT, Outsourcing, Working Hours, and Termination",
    category: "Pengupahan & PHK",
    categoryEn: "Wages & Termination",
    type: "government-regulation",
    year: 2021,
    status: "active",
    summary: "Aturan pelaksanaan UU Cipta Kerja yang mengatur secara detail tentang PKWT (kontrak), outsourcing, waktu kerja, lembur, dan mekanisme PHK serta perhitungan pesangon.",
    summaryEn: "Implementing regulation of the Job Creation Law detailing PKWT (contracts), outsourcing, working hours, overtime, termination mechanisms, and severance calculations.",
    keyPoints: [
      "PKWT untuk pekerjaan tertentu, maks 5 tahun",
      "Kompensasi PKWT diberikan saat kontrak berakhir",
      "Alih daya hanya untuk pekerjaan penunjang",
      "Lembur max 4 jam/hari, 18 jam/minggu",
      "Pesangon PHK: 0.5x - 1x ketentuan lama tergantung alasan",
    ],
    keyPointsEn: [
      "PKWT for specific work, max 5 years",
      "PKWT compensation paid upon contract end",
      "Outsourcing only for non-core work",
      "Overtime max 4 hours/day, 18 hours/week",
      "Severance: 0.5x - 1x of old provisions depending on reason",
    ],
  },
  {
    id: "pp-36-2021",
    title: "PP No. 36 Tahun 2021 tentang Pengupahan",
    titleEn: "Government Regulation No. 36/2021 on Wages",
    category: "Pengupahan & PHK",
    categoryEn: "Wages & Termination",
    type: "government-regulation",
    year: 2021,
    status: "amended",
    summary: "Mengatur kebijakan pengupahan nasional termasuk upah minimum (UMP/UMK), struktur skala upah, upah lembur, dan sanksi bagi pelanggar ketentuan upah.",
    summaryEn: "Regulates national wage policy including minimum wage (UMP/UMK), wage structure and scale, overtime pay, and sanctions for wage violations.",
    keyPoints: [
      "Upah minimum ditetapkan oleh gubernur setiap tahun",
      "Formula UM: UM(t) x (PE + α)",
      "Struktur dan skala upah wajib bagi perusahaan",
      "Upah lembur: 1/173 x gaji sebulan",
      "Sanksi administratif bagi yang bayar di bawah UMP",
    ],
    keyPointsEn: [
      "Minimum wage set by governor annually",
      "MW formula: UM(t) x (PE + α)",
      "Wage structure and scale mandatory for companies",
      "Overtime pay: 1/173 x monthly salary",
      "Administrative sanctions for paying below minimum wage",
    ],
  },
  {
    id: "pp-51-2023",
    title: "PP No. 51 Tahun 2023 tentang Perubahan PP Pengupahan",
    titleEn: "Government Regulation No. 51/2023 Amending Wage Regulation",
    category: "Pengupahan & PHK",
    categoryEn: "Wages & Termination",
    type: "government-regulation",
    year: 2023,
    status: "active",
    summary: "Mengubah PP 36/2021 dengan formula baru upah minimum yang mempertimbangkan pertumbuhan ekonomi, inflasi, dan indeks kontribusi tenaga kerja.",
    summaryEn: "Amends PP 36/2021 with a new minimum wage formula considering economic growth, inflation, and labor contribution index.",
    keyPoints: [
      "Formula baru UM(t+1) = UM(t) + (PE + α)",
      "Variabel α berkisar 0.10 - 0.30",
      "UMK ditetapkan jika selisih UMP > UMK sebelumnya",
      "Usaha mikro dikecualikan dari upah minimum",
      "Berlaku mulai Januari 2024",
    ],
    keyPointsEn: [
      "New formula UM(t+1) = UM(t) + (PE + α)",
      "α variable ranges 0.10 - 0.30",
      "City/Regency MW set if different from province",
      "Micro businesses exempted from minimum wage",
      "Effective from January 2024",
    ],
  },
  {
    id: "pp-37-2021",
    title: "PP No. 37 Tahun 2021 tentang Penyelenggaraan TKA",
    titleEn: "Government Regulation No. 37/2021 on Foreign Worker Management",
    category: "Tenaga Kerja Asing",
    categoryEn: "Foreign Workers",
    type: "government-regulation",
    year: 2021,
    status: "active",
    summary: "Mengatur penggunaan Tenaga Kerja Asing (TKA) di Indonesia, termasuk RPTKA, jabatan yang boleh diduduki TKA, dan kewajiban perusahaan pengguna.",
    summaryEn: "Regulates the use of Foreign Workers (TKA) in Indonesia, including RPTKA, positions open to foreign workers, and obligations of user companies.",
    keyPoints: [
      "Setiap TKA wajib memiliki RPTKA",
      "Jabatan tertentu dilarang untuk TKA (HR, legal, dll)",
      "TKA wajib memiliki kompetensi bahasa Indonesia",
      "Perusahaan wajib menunjuk TKA pendamping",
      "RPTKA berlaku max 2 tahun, dapat diperpanjang",
    ],
    keyPointsEn: [
      "Every foreign worker must have RPTKA",
      "Certain positions prohibited for foreign workers (HR, legal, etc.)",
      "Foreign workers must have Indonesian language competency",
      "Companies must appoint counterpart local workers",
      "RPTKA valid max 2 years, extendable",
    ],
  },
  {
    id: "permenaker-18-2018",
    title: "Permenaker No. 18 Tahun 2018 tentang TKA",
    titleEn: "Minister Regulation No. 18/2018 on Foreign Workers",
    category: "Tenaga Kerja Asing",
    categoryEn: "Foreign Workers",
    type: "minister-regulation",
    year: 2018,
    status: "active",
    summary: "Ketentuan teknis penggunaan TKA termasuk prosedur pengajuan RPTKA, pengalihan keahlian, dan pengawasan tenaga kerja asing.",
    summaryEn: "Technical provisions for foreign worker employment including RPTKA application procedures, skills transfer, and foreign worker supervision.",
    keyPoints: [
      "RPTKA diajukan secara elektronik",
      "Pengalihan keahlian kepada TKA pendamping",
      "TKA dilarang memangku jabatan HRD",
      "Wajib lapor TKA secara berkala",
      "Sanksi pidana bagi pelanggar ketentuan TKA",
    ],
    keyPointsEn: [
      "RPTKA submitted electronically",
      "Skills transfer to counterpart local workers",
      "Foreign workers prohibited from HR positions",
      "Periodic reporting required",
      "Criminal sanctions for violations",
    ],
  },
  {
    id: "permenaker-1-2017",
    title: "Permenaker No. 1 Tahun 2017 tentang Struktur dan Skala Upah",
    titleEn: "Minister Regulation No. 1/2017 on Wage Structure and Scale",
    category: "Pengupahan & PHK",
    categoryEn: "Wages & Termination",
    type: "minister-regulation",
    year: 2017,
    status: "active",
    summary: "Mewajibkan perusahaan menyusun struktur dan skala upah sebagai pedoman penetapan gaji karyawan berdasarkan golongan jabatan, masa kerja, dan kinerja.",
    summaryEn: "Requires companies to prepare wage structure and scale as guidelines for employee salary determination based on job classification, tenure, and performance.",
    keyPoints: [
      "Wajib bagi perusahaan dengan minimal 1 karyawan",
      "Didasarkan pada golongan jabatan dan masa kerja",
      "Struktur upah dari terendah ke tertinggi",
      "Skala upah berupa kisaran nominal per golongan",
      "Dibuat dengan memperhatikan kemampuan perusahaan",
    ],
    keyPointsEn: [
      "Mandatory for companies with at least 1 employee",
      "Based on job classification and tenure",
      "Wage structure from lowest to highest",
      "Wage scale as nominal range per classification",
      "Prepared considering company capability",
    ],
  },
  {
    id: "permenaker-6-2016",
    title: "Permenaker No. 6 Tahun 2016 tentang THR Keagamaan",
    titleEn: "Minister Regulation No. 6/2016 on Religious Holiday Allowance (THR)",
    category: "Pengupahan & PHK",
    categoryEn: "Wages & Termination",
    type: "minister-regulation",
    year: 2016,
    status: "active",
    summary: "Mengatur kewajiban perusahaan membayar THR kepada pekerja paling lambat H-7 hari raya keagamaan. THR = 1 bulan gaji bagi pekerja dengan masa kerja ≥ 12 bulan.",
    summaryEn: "Regulates company obligation to pay THR to workers no later than H-7 of religious holidays. THR = 1 month salary for workers with ≥ 12 months service.",
    keyPoints: [
      "THR wajib dibayarkan H-7 sebelum hari raya",
      "Masa kerja ≥ 12 bulan: 1 bulan gaji",
      "Masa kerja 1-12 bulan: proporsional",
      "Denda keterlambatan 5% dari total THR",
      "Sanksi pidana jika tidak membayar THR",
    ],
    keyPointsEn: [
      "THR must be paid H-7 before religious holiday",
      "Service ≥ 12 months: 1 month salary",
      "Service 1-12 months: proportional",
      "Late penalty: 5% of total THR",
      "Criminal sanctions for non-payment",
    ],
  },
  {
    id: "pp-82-2019",
    title: "PP No. 82/2019 jo. PP 49/2023 tentang BPJS",
    titleEn: "Government Regulation No. 82/2019 jo. 49/2023 on BPJS",
    category: "BPJS & Jaminan Sosial",
    categoryEn: "BPJS & Social Security",
    type: "government-regulation",
    year: 2023,
    status: "active",
    summary: "Perubahan iuran BPJS Ketenagakerjaan. Iuran JHT 5.7% (3.7% perusahaan, 2% pekerja), JP 3% (2% perusahaan, 1% pekerja), JKK 0.24%-1.74%, JKM 0.3%.",
    summaryEn: "Changes to BPJS Ketenagakerjaan contributions. JHT 5.7% (3.7% company, 2% worker), JP 3% (2% company, 1% worker), JKK 0.24%-1.74%, JKM 0.3%.",
    keyPoints: [
      "JHT: 3.7% perusahaan + 2% pekerja = 5.7%",
      "JP (Pensiun): 2% perusahaan + 1% pekerja = 3%",
      "JKK: 0.24%-1.74% (tergantung risiko)",
      "JKM: 0.3% dibayar perusahaan",
      "BPJS Kesehatan: 4% perusahaan + 1% pekerja = 5%",
    ],
    keyPointsEn: [
      "JHT: 3.7% company + 2% worker = 5.7%",
      "JP (Pension): 2% company + 1% worker = 3%",
      "JKK: 0.24%-1.74% (depending on risk level)",
      "JKM: 0.3% paid by company",
      "BPJS Kesehatan: 4% company + 1% worker = 5%",
    ],
  },
  {
    id: "per-1-pj-2024",
    title: "PER-1/PJ/2024 tentang Tarif Efektif Rata-rata (TER) PPh 21",
    titleEn: "PER-1/PJ/2024 on Average Effective Tax Rate (TER) PPh 21",
    category: "Perpajakan",
    categoryEn: "Taxation",
    type: "finance-regulation",
    year: 2024,
    status: "active",
    summary: "Memberlakukan sistem TER untuk pemotongan PPh 21 bulanan. Menggantikan tarif Pasal 17 lama. TER dibagi dalam 3 kategori (A, B, C) berdasarkan PTKP.",
    summaryEn: "Implements TER system for monthly PPh 21 withholding. Replaces old Article 17 rates. TER divided into 3 categories (A, B, C) based on PTKP status.",
    keyPoints: [
      "TER kategori A: wajib pajak dengan PTKP TK/0 - TK/3",
      "TER kategori B: wajib pajak dengan PTKP K/0 - K/3",
      "TER kategori C: wajib pajak dengan PTKP K/I/0 - K/I/3",
      "Perhitungan final dilakukan di Desember",
      "Berlaku mulai Januari 2024",
    ],
    keyPointsEn: [
      "TER category A: taxpayers with PTKP TK/0 - TK/3",
      "TER category B: taxpayers with PTKP K/0 - K/3",
      "TER category C: taxpayers with PTKP K/I/0 - K/I/3",
      "Final calculation performed in December",
      "Effective from January 2024",
    ],
  },
  {
    id: "pmk-168-2023",
    title: "PMK No. 168 Tahun 2023 tentang PTKP dan Tarif PPh 21",
    titleEn: "Finance Minister Regulation No. 168/2023 on PTKP and PPh 21 Rates",
    category: "Perpajakan",
    categoryEn: "Taxation",
    type: "finance-regulation",
    year: 2023,
    status: "active",
    summary: "Menyesuaikan besaran PTKP dan tarif PPh 21. PTKP tetap: Rp 54 juta (TK/0), tambahan Rp 4.5 juta per tanggungan. Tarif progresif 5%-35%.",
    summaryEn: "Adjusts PTKP amounts and PPh 21 rates. PTKP unchanged: Rp 54 million (TK/0), additional Rp 4.5 million per dependent. Progressive rates 5%-35%.",
    keyPoints: [
      "PTKP TK/0: Rp 54.000.000/tahun",
      "Tambahan tanggungan: Rp 4.500.000/orang",
      "Tambahan kawin: Rp 4.500.000",
      "Lapisan PKP: 5%, 15%, 25%, 30%, 35%",
      "Tarif PPh Badan: 22%",
    ],
    keyPointsEn: [
      "PTKP TK/0: Rp 54,000,000/year",
      "Additional dependent: Rp 4,500,000/person",
      "Marriage addition: Rp 4,500,000",
      "Taxable income layers: 5%, 15%, 25%, 30%, 35%",
      "Corporate tax rate: 22%",
    ],
  },
  {
    id: "pp-50-2012",
    title: "PP No. 50 Tahun 2012 tentang SMK3",
    titleEn: "Government Regulation No. 50/2012 on OSH Management System",
    category: "K3 & SMK3",
    categoryEn: "OHS & SMK3",
    type: "government-regulation",
    year: 2012,
    status: "active",
    summary: "Mewajibkan perusahaan menerapkan Sistem Manajemen K3 (SMK3). Perusahaan dengan >100 karyawan wajib SMK3. Perusahaan <100 karyawan wajib pedoman K3.",
    summaryEn: "Requires companies to implement OSH Management System (SMK3). Companies with >100 employees must have SMK3. Companies with <100 employees must have OHS guidelines.",
    keyPoints: [
      "SMK3 wajib bagi perusahaan >100 karyawan",
      "Perusahaan <100 karyawan wajib pedoman K3",
      "Audit SMK3 setiap 3 tahun",
      "5 tingkat kematangan SMK3",
      "Sanksi pidana bagi pelanggar K3",
    ],
    keyPointsEn: [
      "SMK3 mandatory for companies >100 employees",
      "Companies <100 employees must have OHS guidelines",
      "SMK3 audit every 3 years",
      "5 levels of SMK3 maturity",
      "Criminal sanctions for OHS violations",
    ],
  },
  {
    id: "permen-esdm-26-2018",
    title: "Permen ESDM No. 26 Tahun 2018 tentang K3 Pertambangan",
    titleEn: "Minister of Energy Regulation No. 26/2018 on Mining OHS",
    category: "K3 & SMK3",
    categoryEn: "OHS & SMK3",
    type: "minister-regulation",
    year: 2018,
    status: "active",
    summary: "Ketentuan K3 spesifik untuk sektor pertambangan. Mengatur SIO operator, POP/POU pengawas, MCU berkala, dan pelaporan kecelakaan tambang ke Inspektur Tambang.",
    summaryEn: "Specific OHS provisions for the mining sector. Regulates operator SIO, supervisor POP/POU, periodic medical checkups, and mining accident reporting to Mine Inspectors.",
    keyPoints: [
      "SIO wajib bagi operator alat berat (excavator, bulldozer, dll)",
      "POP wajib bagi pengawas lapangan level pertama",
      "POU wajib bagi pengawas senior/manager tambang",
      "MCU berkala setiap 12 bulan",
      "Kecelakaan tambang wajib dilaporkan ke Inspektur Tambang",
    ],
    keyPointsEn: [
      "SIO mandatory for heavy equipment operators (excavator, bulldozer, etc.)",
      "POP mandatory for first-level field supervisors",
      "POU mandatory for senior supervisors/mine managers",
      "Periodic medical checkup every 12 months",
      "Mining accidents must be reported to Mine Inspector",
    ],
  },
  {
    id: "pmk-64-2020",
    title: "PMK 64/2020 jo. 65/2020 tentang Batas Upah BPJS Kesehatan",
    titleEn: "Finance Minister Regulation 64/2020 jo. 65/2020 on BPJS Health Wage Cap",
    category: "BPJS & Jaminan Sosial",
    categoryEn: "BPJS & Social Security",
    type: "finance-regulation",
    year: 2020,
    status: "active",
    summary: "Menetapkan batas maksimal upah untuk perhitungan iuran BPJS Kesehatan sebesar Rp 12.000.000 per bulan. Iuran 5% dari upah (4% perusahaan + 1% pekerja).",
    summaryEn: "Sets maximum wage cap for BPJS Health contribution calculation at Rp 12,000,000 per month. Contribution 5% of wage (4% company + 1% worker).",
    keyPoints: [
      "Batas upah BPJS Kesehatan: Rp 12.000.000",
      "Iuran maksimal: Rp 600.000/bulan",
      "4% perusahaan = Rp 480.000",
      "1% pekerja = Rp 120.000",
      "Kelas perawatan berdasarkan iuran",
    ],
    keyPointsEn: [
      "BPJS Health wage cap: Rp 12,000,000",
      "Maximum contribution: Rp 600,000/month",
      "4% company = Rp 480,000",
      "1% worker = Rp 120,000",
      "Treatment class based on contribution",
    ],
  },
  {
    id: "permenaker-16-2015",
    title: "Permenaker No. 16 Tahun 2015 tentang BPJS Ketenagakerjaan",
    titleEn: "Minister Regulation No. 16/2015 on BPJS Ketenagakerjaan",
    category: "BPJS & Jaminan Sosial",
    categoryEn: "BPJS & Social Security",
    type: "minister-regulation",
    year: 2015,
    status: "active",
    summary: "Tata cara pendaftaran dan pelaporan iuran BPJS Ketenagakerjaan. Perusahaan wajib mendaftarkan pekerja paling lambat 10 hari setelah mempekerjakan.",
    summaryEn: "Procedures for registration and reporting of BPJS Ketenagakerjaan contributions. Companies must register workers no later than 10 days after hiring.",
    keyPoints: [
      "Pendaftaran maksimal 10 hari setelah pekerja mulai",
      "Pelaporan iuran setiap bulan",
      "Sanksi denda 2% per bulan keterlambatan",
      "Pekerja asing wajib didaftarkan JKK saja",
      "Data peserta dilaporkan secara elektronik",
    ],
    keyPointsEn: [
      "Registration maximum 10 days after worker starts",
      "Monthly contribution reporting",
      "Late penalty 2% per month",
      "Foreign workers only registered for JKK",
      "Participant data reported electronically",
    ],
  },
  {
    id: "pp-38-2021",
    title: "PP No. 38 Tahun 2021 tentang PKWT Kompensasi",
    titleEn: "Government Regulation No. 38/2021 on PKWT Compensation",
    category: "Pengupahan & PHK",
    categoryEn: "Wages & Termination",
    type: "government-regulation",
    year: 2021,
    status: "active",
    summary: "Mengatur kompensasi yang wajib dibayarkan kepada pekerja PKWT saat kontrak berakhir. Besaran kompensasi dihitung berdasarkan masa kerja dan upah.",
    summaryEn: "Regulates compensation that must be paid to PKWT workers upon contract termination. Compensation amount calculated based on service period and wages.",
    keyPoints: [
      "Kompensasi PKWT diberikan saat kontrak berakhir",
      "Perhitungan: 1/12 x upah per bulan x masa kerja",
      "Dibayar dalam bentuk uang tunai",
      "Tidak berlaku jika PKWT diperpanjang dengan kontrak baru",
      "Kompensasi bukan pesangon",
    ],
    keyPointsEn: [
      "PKWT compensation paid upon contract termination",
      "Calculation: 1/12 x monthly wage x months of service",
      "Paid in cash",
      "Does not apply if PKWT is extended with new contract",
      "Compensation is not severance pay",
    ],
  },
  {
    id: "pp-39-2021",
    title: "PP No. 39 Tahun 2021 tentang Upah Minimum",
    titleEn: "Government Regulation No. 39/2021 on Minimum Wage",
    category: "Pengupahan & PHK",
    categoryEn: "Wages & Termination",
    type: "government-regulation",
    year: 2021,
    status: "replaced",
    summary: "Ketentuan awal upah minimum pasca UU Cipta Kerja. Telah digantikan oleh PP 51/2023 dengan formula penghitungan baru.",
    summaryEn: "Initial minimum wage provisions post Job Creation Law. Has been replaced by PP 51/2023 with new calculation formula.",
    keyPoints: [
      "Digantikan oleh PP 51/2023",
      "Formula lama menggunakan inflasi dan pertumbuhan ekonomi",
      "UMK tidak wajib jika selisih dengan UMP kecil",
      "Usaha mikro dan kecil dikecualikan",
    ],
    keyPointsEn: [
      "Replaced by PP 51/2023",
      "Old formula used inflation and economic growth",
      "City MW not mandatory if difference with province MW is small",
      "Micro and small businesses exempted",
    ],
  },
];

export const REGULATION_CATEGORIES = [
  ...new Set(REGULATIONS.map((r) => r.category)),
];

export const ENQUIRY_STATUSES = ["open", "in-progress", "resolved", "closed"] as const;
export const ENQUIRY_PRIORITIES = ["low", "medium", "high", "urgent"] as const;

export type EnquiryStatus = typeof ENQUIRY_STATUSES[number];
export type EnquiryPriority = typeof ENQUIRY_PRIORITIES[number];
